import {
  BANNED_PHRASES,
  BEATS,
  MAX_WORDS_PER_SCENE,
  WORDS_PER_SECOND,
  type Beat,
} from "@/lib/insight-script";

/**
 * A render manifest: everything a generated-video pipeline needs, in one object.
 *
 * ## Why this is separate from `insight-script.ts`
 *
 * That module validates a script that will be illustrated with *stills* — the
 * pictures are generated once and panned across, so a scene needs narration, a
 * brief and a beat. A manifest is for clips generated by a video model, and it
 * carries three things a still never needs: a camera move the model must
 * execute, a prompt written to a fixed word order, and a seed.
 *
 * The seed is the one that changes how the pipeline behaves rather than what it
 * produces. Video generation has a real reject rate — the honest planning
 * number is about 1.6 renders per accepted clip — and without a stored seed the
 * only way to fix one bad clip out of eleven is to re-roll all of them and hope.
 * With it, ten clips stay byte-identical and one is re-rolled. On a format that
 * costs dollars a video rather than cents, that is the difference between
 * iterating and starting again.
 *
 * ## Why the gate is here and not in the renderer
 *
 * Every check below costs nothing and runs before a single billed second. A
 * manifest with a nine-word prompt or a thirteenth clip is cheapest to reject
 * now; the same manifest discovered at assembly has already spent the money.
 * This is the same argument `insight-script.ts` makes one stage earlier, and it
 * matters more here because the stage it guards is roughly fifty times dearer.
 */

/** Clip length the format cuts at. Below four seconds a generated clip has no
 *  time to complete its one camera move; above five the shot outstays the
 *  sentence under it. */
export const MIN_CLIP_SECONDS = 4.0;
export const MAX_CLIP_SECONDS = 5.0;

/** How many clips a 45–55 second video is. Fewer and the cutting rhythm that
 *  defines the genre is gone; more and each clip is too short to move. */
export const MIN_CLIPS = 10;
export const MAX_CLIPS = 12;

/** Prompt length. Under 45 words the model invents the half you left out; over
 *  70 it starts discarding the beginning, which is where the shot size and the
 *  subject live. */
export const MIN_PROMPT_WORDS = 45;
export const MAX_PROMPT_WORDS = 70;

/**
 * The only camera moves allowed.
 *
 * A closed list because this is what the genre *is*: the footage is slow and
 * every bit of energy comes from the edit. One handheld or whip pan among
 * eleven locked-off shots does not read as variety, it reads as a different
 * video spliced in. Also, a model given "orbit" or "drone" will happily produce
 * something that cannot be cut against the rest at all.
 */
export const CAMERA_MOVES = [
  "slow push in",
  "slow pull out",
  "slow drift left",
  "slow drift right",
  "rack focus",
  "locked off",
] as const;

export type CameraMove = (typeof CAMERA_MOVES)[number];

/**
 * Words that must never appear in a clip prompt.
 *
 * Anything that makes the model bake pixels the edit is going to add anyway.
 * Burned-in text is the expensive one: a caption the model drew cannot be
 * removed, cannot be restyled, and will sit underneath the real caption for the
 * whole clip.
 */
export const FORBIDDEN_IN_PROMPT = [
  "text",
  "subtitle",
  "caption",
  "logo",
  "brand",
  "sign",
  "screen",
  "watermark",
  "chart",
  "diagram",
  "ui",
] as const;

export interface ManifestClip {
  id: number;
  beat: string;
  start: number;
  duration: number;
  narration: string;
  caption: string;
  /** The one word in `caption` to colour. */
  captionHighlight: string;
  emphasis: string[];
  cameraMove: string;
  /** The text-to-video prompt, without the style lock — see `Manifest`. */
  prompt: string;
  /** Pinned, so one bad clip is re-rolled alone. */
  seed: number;
}

export interface Manifest {
  conceptName: string;
  aspectRatio: string;
  /**
   * The look, appended to every clip prompt **by the renderer, never by the
   * model**.
   *
   * Left in the model's output it is twenty words it can paraphrase eleven
   * different ways, and "video looks like twelve different films" is the
   * commonest failure of this genre. Appended in code it is the same twenty
   * words on every clip, and changing the look is one edit rather than a
   * regeneration.
   */
  styleLock: string;
  negativePrompt: string;
  clips: ManifestClip[];
}

export interface ManifestCheck {
  ok: boolean;
  /** Whole sentences, safe to append to a retry prompt verbatim. */
  errors: string[];
}

function words(text: string): number {
  const trimmed = text.trim();

  return trimmed.length === 0 ? 0 : trimmed.split(/\s+/).length;
}

/**
 * Everything that can be checked before a billed second is spent.
 *
 * Deliberately strict about the prompt's *shape* rather than its content: a
 * prompt that is the right length, names one allowed move and asks for no text
 * is one a model can execute. Whether it is a good shot is a judgement no
 * validator makes, and pretending otherwise would reject workable manifests.
 */
export function checkManifest(manifest: Manifest): ManifestCheck {
  const errors: string[] = [];
  const clips = manifest.clips;

  if (clips.length < MIN_CLIPS || clips.length > MAX_CLIPS) {
    errors.push(
      `The manifest has ${clips.length} clips. It must have between ` +
        `${MIN_CLIPS} and ${MAX_CLIPS}.`,
    );
  }

  const narration = clips.map((clip) => clip.narration).join(" ");
  const totalWords = words(narration);
  const haystack = narration.toLowerCase();

  for (const phrase of BANNED_PHRASES) {
    if (haystack.includes(phrase)) {
      errors.push(`Remove the phrase "${phrase}". It is banned in this format.`);
    }
  }

  for (const clip of clips) {
    if (clip.duration < MIN_CLIP_SECONDS || clip.duration > MAX_CLIP_SECONDS) {
      errors.push(
        `Clip ${clip.id} is ${clip.duration}s. Every clip must run between ` +
          `${MIN_CLIP_SECONDS} and ${MAX_CLIP_SECONDS} seconds.`,
      );
    }

    const sentence = words(clip.narration);

    if (sentence > MAX_WORDS_PER_SCENE) {
      errors.push(
        `Clip ${clip.id}'s narration is ${sentence} words. No sentence may ` +
          `exceed ${MAX_WORDS_PER_SCENE}.`,
      );
    }

    const promptWords = words(clip.prompt);

    if (promptWords < MIN_PROMPT_WORDS || promptWords > MAX_PROMPT_WORDS) {
      errors.push(
        `Clip ${clip.id}'s prompt is ${promptWords} words. It must be between ` +
          `${MIN_PROMPT_WORDS} and ${MAX_PROMPT_WORDS}.`,
      );
    }

    // Counted, not merely detected: a prompt naming two moves is a prompt the
    // model resolves by picking one, and which one is not predictable.
    const named = CAMERA_MOVES.filter((move) =>
      clip.prompt.toLowerCase().includes(move),
    );

    if (!CAMERA_MOVES.includes(clip.cameraMove as CameraMove)) {
      errors.push(
        `Clip ${clip.id} asks for the camera move "${clip.cameraMove}", which ` +
          `is not allowed. Use one of: ${CAMERA_MOVES.join(", ")}.`,
      );
    } else if (named.length !== 1) {
      errors.push(
        `Clip ${clip.id}'s prompt names ${named.length} camera moves. It must ` +
          `name exactly one, and it must be "${clip.cameraMove}".`,
      );
    }

    const prompt = clip.prompt.toLowerCase();

    for (const forbidden of FORBIDDEN_IN_PROMPT) {
      // Word-boundary matched: "screen" must not fire on "screenwriter", and
      // "sign" must not fire on "designer" or "resigned".
      if (new RegExp(`\\b${forbidden}\\b`).test(prompt)) {
        errors.push(
          `Clip ${clip.id}'s prompt asks for "${forbidden}" in frame. Captions ` +
            `and graphics are added in the edit, never generated.`,
        );
      }
    }

    if (!clip.caption.toUpperCase().includes(clip.captionHighlight.toUpperCase())) {
      errors.push(
        `Clip ${clip.id} highlights "${clip.captionHighlight}", which is not in ` +
          `its caption "${clip.caption}".`,
      );
    }

    if (!Number.isInteger(clip.seed)) {
      errors.push(
        `Clip ${clip.id} has no usable seed. Without one a bad clip cannot be ` +
          `re-rolled without changing every other clip.`,
      );
    }
  }

  const beats = new Set(clips.map((clip) => clip.beat));

  for (const beat of BEATS) {
    if (!beats.has(beat)) {
      errors.push(`The manifest has no ${beat} beat. All six are required.`);
    }
  }

  const order = clips.map((clip) => BEATS.indexOf(clip.beat as Beat));

  for (let index = 1; index < order.length; index += 1) {
    if (order[index] !== -1 && order[index - 1] !== -1 && order[index] < order[index - 1]) {
      errors.push(
        `Clip ${clips[index].id} is a ${clips[index].beat} beat after a ` +
          `${clips[index - 1].beat} beat. The six beats must run in order.`,
      );
      break;
    }
  }

  // The one check that catches a manifest which is internally consistent and
  // still wrong: eleven perfectly-formed clips whose total does not match the
  // words spoken over them produces a video whose picture runs ahead of its
  // narration, and nothing downstream notices.
  const declared = clips.reduce((sum, clip) => sum + clip.duration, 0);
  const spoken = totalWords / WORDS_PER_SECOND;

  if (Math.abs(declared - spoken) > 2) {
    errors.push(
      `The clips declare ${declared.toFixed(1)}s but ${totalWords} words takes ` +
        `about ${spoken.toFixed(1)}s to say. Bring the two within 2s.`,
    );
  }

  return { ok: errors.length === 0, errors };
}

/**
 * What is actually sent to the video model for one clip.
 *
 * The style lock is appended here rather than being part of the prompt the
 * model wrote, so all eleven clips carry byte-identical look instructions. See
 * `Manifest.styleLock`.
 */
export function clipPrompt(manifest: Manifest, clip: ManifestClip): string {
  return `${clip.prompt}, ${manifest.styleLock}`;
}

/**
 * What one manifest will cost to render, in billed seconds.
 *
 * Models bill whole seconds and round up, so a 4.5s clip is charged as 5. The
 * reject multiplier is the honest part: video generation does not succeed first
 * time, and a cost model that assumes it does is wrong by more than the
 * difference between any two providers.
 */
export function billedSeconds(manifest: Manifest, rejectRate = 1.6): number {
  const seconds = manifest.clips.reduce(
    (sum, clip) => sum + Math.ceil(clip.duration),
    0,
  );

  return Math.ceil(seconds * rejectRate);
}
