import { describe, expect, it, vi } from "vitest";

import { GatewayImageProvider } from "@/services/providers/image.provider";

describe("GatewayImageProvider", () => {
  it("returns the generated bytes and the model that made them", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1, 2, 3]) },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a city at night",
      aspectRatio: "16:9",
    });

    expect(result.data).toEqual(Buffer.from([1, 2, 3]));
    expect(result.model).toBeTruthy();
  });

  it("passes the aspect ratio through", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
    });

    await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(generate.mock.calls[0][0].aspectRatio).toBe("1:1");
  });

  it("raises a retryable ProviderError when the gateway is unreachable", async () => {
    const generate = vi.fn().mockRejectedValue(new Error("ECONNRESET"));

    await expect(
      new GatewayImageProvider(generate).generate({
        prompt: "x",
        aspectRatio: "16:9",
      }),
    ).rejects.toMatchObject({ retryable: true });
  });
});
