import { describe, expect, it, vi } from "vitest";

import { GatewayImageProvider } from "@/services/providers/image.provider";

describe("GatewayImageProvider", () => {
  it("returns the generated bytes and the model that made them", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1, 2, 3]) },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a city at night",
      aspectRatio: "16:9",
    });

    expect(result.data).toEqual(Buffer.from([1, 2, 3]));
    expect(result.model).toBeTruthy();
  });

  it("passes the aspect ratio through", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
    });

    await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(generate.mock.calls[0][0].aspectRatio).toBe("1:1");
  });

  it("reports the model the response says actually ran, not the one requested", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
      responses: [{ modelId: "openai/gpt-image-1-mini", timestamp: new Date() }],
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(result.model).toBe("openai/gpt-image-1-mini");
  });

  it("falls back to the configured model when the response reports none", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
      responses: [],
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(result.model).toBeTruthy();
    expect(result.model).not.toBe("openai/gpt-image-1-mini");
  });

  it("passes reference images through, which is the character-consistency mechanism", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
    });
    const sheet = Buffer.from([9, 8, 7]);

    await new GatewayImageProvider(generate).generate({
      prompt: "the bear on a forest path",
      aspectRatio: "9:16",
      size: "1024x1536",
      referenceImages: [sheet],
    });

    const call = generate.mock.calls[0][0];
    expect(call.prompt.text).toBe("the bear on a forest path");
    expect(call.prompt.images).toHaveLength(1);
    expect(Buffer.from(call.prompt.images[0])).toEqual(sheet);
    // Pixels win over the ratio — the SDK warns if both arrive.
    expect(call.size).toBe("1024x1536");
    expect(call.aspectRatio).toBeUndefined();
  });

  it("sends a bare string prompt when there is nothing to condition on", async () => {
    // Logos and thumbnails must keep making exactly the call they always have.
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
    });

    await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(generate.mock.calls[0][0].prompt).toBe("a logo");
    expect(generate.mock.calls[0][0].size).toBeUndefined();
  });

  it("prices the image from the tokens the provider reported", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
      responses: [{ modelId: "openai/gpt-image-2", timestamp: new Date() }],
      usage: { inputTokens: 1150, outputTokens: 1372, totalTokens: 2522 },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a scene",
      aspectRatio: "9:16",
      model: "openai/gpt-image-2",
    });

    // $5/M in, $30/M out — the gateway's own listed rate for this model.
    expect(result.costUsd).toBeCloseTo((1150 * 5 + 1372 * 30) / 1_000_000, 8);
    // Rounded, this is the $0.047 every cost table in the spec is written
    // against.
    expect(Number(result.costUsd.toFixed(3))).toBe(0.047);
    // And the counts it was derived from, so the figure above can be checked
    // against a gateway invoice rather than taken on trust.
    expect(result.inputTokens).toBe(1150);
    expect(result.outputTokens).toBe(1372);
  });

  it("keeps the input count when the provider omits the output one, which is where $0.006 comes from", async () => {
    // This is the whole reason `inputTokens`/`outputTokens` exist.
    // `ImageModelV4Usage` types both as `number | undefined`, and a response
    // that omits `outputTokens` prices the very same picture at $0.00575 —
    // which `.toFixed(3)` renders as exactly "$0.006", the figure the operator
    // reported and assumed was a price. With only `costUsd` recorded, a broken
    // meter and a cheap model are the same row; with the raw counts recorded,
    // a missing `out` is visible on its face.
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
      responses: [{ modelId: "openai/gpt-image-2", timestamp: new Date() }],
      usage: { inputTokens: 1150 },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a scene",
      aspectRatio: "9:16",
      model: "openai/gpt-image-2",
    });

    expect(result.costUsd).toBeCloseTo(0.00575, 8);
    expect(result.costUsd.toFixed(3)).toBe("0.006");
    expect(result.inputTokens).toBe(1150);
    expect(result.outputTokens).toBeUndefined();
  });

  it("omits both counts entirely when the provider reports no usage at all", async () => {
    // Absent keys rather than two zeroes: a zero is a measurement, and "the
    // provider told us nothing" is not one.
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(result).not.toHaveProperty("inputTokens");
    expect(result).not.toHaveProperty("outputTokens");
  });

  it("prices a thumbnail rather than recording it as free", async () => {
    // `openai/gpt-image-1` is AI_IMAGE_MODEL's default, so this is every
    // thumbnail and every channel logo. It had no entry in `cost.ts`'s rate
    // table, and an unlisted model prices at exactly $0.00 — which reads as a
    // thumbnail that was never generated.
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
      responses: [{ modelId: "openai/gpt-image-1", timestamp: new Date() }],
      usage: { inputTokens: 200, outputTokens: 1056 },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a thumbnail",
      aspectRatio: "16:9",
      model: "openai/gpt-image-1",
    });

    // $5/M in, $40/M out, read off the gateway's model list.
    expect(result.costUsd).toBeCloseTo((200 * 5 + 1056 * 40) / 1_000_000, 8);
    expect(result.costUsd).toBeGreaterThan(0);
  });

  it("prices an unlisted model or a usage-less response at zero, not at a guess", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a logo",
      aspectRatio: "1:1",
    });

    expect(result.costUsd).toBe(0);
  });

  it("asks for the model the caller named rather than the configured default", async () => {
    const generate = vi.fn().mockResolvedValue({
      image: { uint8Array: new Uint8Array([1]) },
      responses: [{ modelId: "openai/gpt-image-2", timestamp: new Date() }],
    });

    const result = await new GatewayImageProvider(generate).generate({
      prompt: "a scene",
      aspectRatio: "9:16",
      model: "openai/gpt-image-2",
    });

    expect(result.model).toBe("openai/gpt-image-2");
  });

  it("marks a 429 or 5xx failure as retryable and everything else as not", async () => {
    const rateLimited = Object.assign(new Error("Too many requests"), {
      statusCode: 429,
    });
    const serverError = Object.assign(new Error("Server error"), {
      statusCode: 503,
    });
    const badRequest = Object.assign(new Error("Bad request"), {
      statusCode: 400,
    });

    await expect(
      new GatewayImageProvider(vi.fn().mockRejectedValue(rateLimited)).generate({
        prompt: "x",
        aspectRatio: "16:9",
      }),
    ).rejects.toMatchObject({ retryable: true });

    await expect(
      new GatewayImageProvider(vi.fn().mockRejectedValue(serverError)).generate({
        prompt: "x",
        aspectRatio: "16:9",
      }),
    ).rejects.toMatchObject({ retryable: true });

    await expect(
      new GatewayImageProvider(vi.fn().mockRejectedValue(badRequest)).generate({
        prompt: "x",
        aspectRatio: "16:9",
      }),
    ).rejects.toMatchObject({ retryable: false });
  });

  it("marks a failure with no HTTP status as not retryable", async () => {
    const generate = vi.fn().mockRejectedValue(new Error("ECONNRESET"));

    await expect(
      new GatewayImageProvider(generate).generate({
        prompt: "x",
        aspectRatio: "16:9",
      }),
    ).rejects.toMatchObject({ retryable: false });
  });
});
