import {
  OPERATOR_EMAIL,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_URL,
} from "@/config/site";

/**
 * schema.org structured data for the public site.
 *
 * ── The honesty rule ────────────────────────────────────────────────────────
 * Everything in this graph has to be true of the code in this repository. That
 * is not a style preference: an `aggregateRating` with no ratings behind it, a
 * `price` with no checkout behind it, or a `review` nobody wrote is a Google
 * structured-data violation *and* exactly the signal a "deceptive site" review
 * looks for. So there is deliberately:
 *
 *   - no `offers` / `price` — this codebase has no payment system at all (no
 *     checkout, no subscription, no card on file), so there is no offer to
 *     describe. Google's software rich result wants `offers` or
 *     `aggregateRating`; going without the rich result is the correct trade.
 *   - no `aggregateRating` or `review` — nobody has rated this.
 *   - no `sameAs` — there is no verified social profile to point at.
 *   - no `screenshot` — none is published, and the OpenGraph card is artwork,
 *     not a screenshot of the app.
 *   - no `datePublished` on the app entity — nothing in the repo establishes a
 *     defensible public release date.
 *
 * ── The shape ───────────────────────────────────────────────────────────────
 * One `@graph` with three nodes joined by `@id` references, rather than three
 * separate `<script>` tags, so the publisher of the site and the author of the
 * software are understood to be the same entity instead of three unrelated
 * ones. `WebApplication` is the accurate subtype of `SoftwareApplication`
 * here — Framecast is used in a browser, not installed.
 */

const ORGANIZATION_ID = `${SITE_URL}/#organization`;
const WEBSITE_ID = `${SITE_URL}/#website`;
const APPLICATION_ID = `${SITE_URL}/#application`;

/**
 * What the pipeline actually does, one capability per line. Each of these maps
 * onto code that exists: script generation from an operator-controlled prompt,
 * ElevenLabs narration, per-line footage matching, the FFmpeg render, the
 * YouTube upload, and the vertical Shorts cut.
 */
const FEATURES = [
  "Writes a sourced script from a topic, using a prompt template you control",
  "Narrates the script with ElevenLabs text-to-speech",
  "Matches stock footage to every line of the script",
  "Renders with FFmpeg: burned-in captions, music bed, sound effects and Ken Burns motion",
  "Publishes to YouTube with a generated title, description, tags and thumbnail",
  "Cuts vertical Shorts from a finished video",
  "Requires human approval of the script before it runs, and of the render before it publishes",
  "Records the third-party API cost of every generation",
  "Self-hosted: the app, the renderer and the database run on one machine",
];

const GRAPH = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": ORGANIZATION_ID,
      name: SITE_NAME,
      url: SITE_URL,
      description:
        "Framecast is a private video production tool, operated by one person.",
      // `/apple-icon` is the 180x180 PNG generated by src/app/apple-icon.tsx.
      // Google asks for a logo of at least 112x112; this clears it and is the
      // same mark the favicon and the app itself use.
      logo: {
        "@type": "ImageObject",
        url: `${SITE_URL}/apple-icon`,
        width: 180,
        height: 180,
      },
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "customer support",
        email: OPERATOR_EMAIL,
        url: `${SITE_URL}/contact`,
        availableLanguage: "English",
      },
    },
    {
      "@type": "WebSite",
      "@id": WEBSITE_ID,
      url: SITE_URL,
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      inLanguage: "en",
      publisher: { "@id": ORGANIZATION_ID },
      // No `potentialAction`/`SearchAction`: there is no site search to point
      // a search box at, and declaring one that 404s is worse than none.
    },
    {
      "@type": "WebApplication",
      "@id": APPLICATION_ID,
      name: SITE_NAME,
      url: SITE_URL,
      description: SITE_DESCRIPTION,
      // schema.org / Google's enumerated category for video and audio tools.
      applicationCategory: "MultimediaApplication",
      applicationSubCategory: "Video production",
      operatingSystem: "Web browser",
      browserRequirements: "Requires JavaScript.",
      softwareRequirements:
        "Self-hosted on Node.js with PostgreSQL and FFmpeg. You supply your own API keys for the script, narration, footage and image providers, and they bill you directly.",
      featureList: FEATURES,
      inLanguage: "en",
      image: `${SITE_URL}/opengraph-image`,
      author: { "@id": ORGANIZATION_ID },
      publisher: { "@id": ORGANIZATION_ID },
      isPartOf: { "@id": WEBSITE_ID },
    },
  ],
};

/**
 * `JSON.stringify` cannot produce a `</script>`, but it happily produces the
 * `<` that starts one if a string ever contains it — which would close this
 * block early and turn the rest of the graph into markup. Escaping `<` to its
 * unicode form is valid inside a JSON string and inert inside HTML, so the
 * payload stays byte-identical to a parser and harmless to the browser.
 */
function serialize(value: unknown) {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

/** Rendered once, in the root layout, so every public page carries it. */
export function SiteStructuredData() {
  return (
    <script
      type="application/ld+json"
      // The content is a compile-time constant from this file — no user input
      // reaches it — and `type="application/ld+json"` is not executed as JS.
      dangerouslySetInnerHTML={{ __html: serialize(GRAPH) }}
    />
  );
}
